
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto_1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLA_SIMPLE = 16;
  public static final int LETRA_MIN = 22;
  public static final int GUION = 18;
  public static final int LETRA_MAY = 23;
  public static final int CONCATENACION = 7;
  public static final int CORCHETE_CIERRA = 6;
  public static final int CORCHETE_ABRE = 5;
  public static final int HASTA = 12;
  public static final int MAYOR_QUE = 19;
  public static final int ID = 2;
  public static final int DOS_PUNTOS = 17;
  public static final int SEPARADOR = 21;
  public static final int STRING = 4;
  public static final int COMA = 13;
  public static final int COMILLA_DOBLE = 15;
  public static final int EOF = 0;
  public static final int DIGITO = 24;
  public static final int CONJ = 3;
  public static final int DISYUNCION = 8;
  public static final int error = 1;
  public static final int OPCIONAL = 11;
  public static final int SALTO_LINEA = 14;
  public static final int PUNTO_COMA = 20;
  public static final int C_KLEENE = 9;
  public static final int ASCII = 25;
  public static final int C_POSITIVA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONJ",
  "STRING",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "CONCATENACION",
  "DISYUNCION",
  "C_KLEENE",
  "C_POSITIVA",
  "OPCIONAL",
  "HASTA",
  "COMA",
  "SALTO_LINEA",
  "COMILLA_DOBLE",
  "COMILLA_SIMPLE",
  "DOS_PUNTOS",
  "GUION",
  "MAYOR_QUE",
  "PUNTO_COMA",
  "SEPARADOR",
  "LETRA_MIN",
  "LETRA_MAY",
  "DIGITO",
  "ASCII"
  };
}

